### ISSUE TITLE
Function for receive message

### ISSUE THREAD

**Issue by reinhart98** [leonjza/pytel#1]

**Comment by reinhart98** [comment]
sorry for asking before, i can see that using pytel we can use the fungction for send message and image. i want to know if there are a function receive a message and read it?

**Comment by leonjza** [comment]
Sorry, this was never implemented. Although I have not used/looked at this code in a very long time, I would suggest you rather look at [Hogar](https://github.com/leonjza/hogar) which can listen for incoming messages.

That said, it may be best to look for another library as even Hogar has not really been maintained.

Good luck!
